# Generated by Django 6.1.1 on 2026-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default=8, upload_to='files/'),
            preserve_default=False,
        ),
    ]
